import { Building2, FileCheck2, LockKeyhole, BarChart3 } from "lucide-react";

export default function EnterprisePage(){return <>
<section className="section border-b border-slate-800 bg-sag-slate/40"><div className="shell"><p className="eyebrow">Enterprise & GovCon cohort center</p><h1 className="h1 mt-4 max-w-5xl">Governed workforce learning for complex organizations and public-sector delivery.</h1><p className="copy mt-6 max-w-3xl">SAG structures role-based cohorts, tenant-isolated learning overlays, evidence reporting and statement-of-work support around operational risk, contract requirements and workforce outcomes.</p></div></section>
<section className="section"><div className="shell grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[[Building2,"B2B cohort architecture","Role pathways, seat models, delivery cadence and controlled rollout."],[LockKeyhole,"Tenant-isolated LMS overlays","Organization-scoped access, version-pinned content and role-based reporting."],[BarChart3,"SLA & evidence reporting","Completion, score, exception and governance reporting aligned to the cohort SOW."],[FileCheck2,"GovCon delivery support","Capability framing, SOW generation requests and contract-to-learning traceability."]].map(([Icon,title,copy])=>{const C=Icon as typeof Building2;return <div key={String(title)} className="panel p-6"><C className="text-sag-gold"/><h2 className="mt-5 text-lg font-semibold">{String(title)}</h2><p className="mt-3 text-sm leading-6 text-sag-muted">{String(copy)}</p></div>})}</div></section>
<section className="section border-y border-slate-800 bg-sag-slate/50"><div className="shell grid gap-10 lg:grid-cols-2"><div><p className="eyebrow">Government contracting posture</p><h2 className="h2 mt-4">Mission-focused, evidence-driven delivery.</h2><p className="copy mt-5">Enterprise and government engagements can be structured around verified corporate representations, contract-specific requirements, controlled deliverables and documented acceptance evidence.</p><div className="mt-6 rounded-xl border border-sag-gold/20 bg-sag-gold/5 p-5 text-sm leading-6 text-slate-200">Any SAM.gov, veteran-owned, SDVOSB/DVOSB, socioeconomic, NAICS or contract representations published here must match the company’s current verified records. This application does not infer or create government status.</div></div><div className="panel p-7"><h3 className="text-xl font-semibold">Typical cohort controls</h3><ul className="mt-5 grid gap-3 text-sm text-sag-muted">{["Exact-version course manifest","Named learner population and role mapping","Tenant and access-control boundary","Assessment and completion threshold","Evidence retention and reporting cadence","Change-control and version transition plan","Registrar and credential eligibility boundary"].map(x=><li key={x} className="flex gap-3"><span className="mt-2 h-1.5 w-1.5 rounded-full bg-sag-gold"/>{x}</li>)}</ul></div></div></section>
<section id="learner-sso" className="section"><div className="shell panel p-8"><p className="eyebrow">Learner SSO</p><h2 className="mt-3 text-3xl font-semibold">Enterprise identity is cohort-controlled.</h2><p className="mt-4 max-w-3xl text-sag-muted">Learner SSO endpoints are issued to authorized cohorts and tenants. Public anonymous enrollment is not enabled from this enterprise site.</p></div></section>
<section id="request" className="section"><div className="shell max-w-4xl"><p className="eyebrow">Request a cohort / SOW</p><h2 className="h2 mt-4">Tell SAG what the workforce must be able to do.</h2><form className="panel mt-8 grid gap-4 p-6 sm:grid-cols-2" action="mailto:info@safetyassuranceglobal.com" method="post" encType="text/plain"><input name="organization" required placeholder="Organization" className="rounded-lg border border-slate-700 bg-slate-950 px-4 py-3"/><input name="contact" required placeholder="Contact name" className="rounded-lg border border-slate-700 bg-slate-950 px-4 py-3"/><input name="email" required type="email" placeholder="Work email" className="rounded-lg border border-slate-700 bg-slate-950 px-4 py-3"/><input name="roles" placeholder="Target roles / learner population" className="rounded-lg border border-slate-700 bg-slate-950 px-4 py-3"/><textarea name="need" required placeholder="Operational need, contract requirement, desired pathway or cohort outcome" className="min-h-36 rounded-lg border border-slate-700 bg-slate-950 px-4 py-3 sm:col-span-2"/><button className="btn-gold sm:col-span-2 sm:justify-self-start">Generate cohort request email</button></form></div></section>
</>}
