import { notFound } from "next/navigation";
import Link from "next/link";
import { academies, academyBySlug } from "@/data/academies";
import { courses } from "@/data/courses";

export function generateStaticParams(){return academies.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const academy=academyBySlug[slug];return academy?{title:academy.name,description:academy.description}:{title:"Academy"}}

export default async function AcademyPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const academy=academyBySlug[slug];if(!academy)notFound();const active=courses.filter(c=>c.academy===academy.code);return <>
<section className="section border-b border-slate-800 bg-grid-dark bg-[size:36px_36px]"><div className="shell"><p className="eyebrow">{academy.code} · Specialized academy</p><h1 className="h1 mt-4 max-w-5xl">{academy.name}</h1><p className="mt-5 text-2xl text-slate-200">{academy.tagline}</p><p className="copy mt-6 max-w-3xl">{academy.description}</p><div className="mt-8 flex flex-wrap gap-3"><Link href="#quote" className="btn-gold">Request Enterprise Quote</Link><Link href="/courses" className="btn-outline">Open Course Registry</Link></div></div></section>
<section className="section"><div className="shell grid gap-6 lg:grid-cols-2"><Info title="Target Roles" items={academy.targetRoles}/><Info title="Operational Pain Points" items={academy.painPoints}/></div></section>
<section className="section border-y border-slate-800 bg-sag-slate/50"><div className="shell"><p className="eyebrow">Packaged pathways</p><h2 className="h2 mt-4">Role-based progression without unnecessary duplication.</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{academy.pathways.map((p,i)=><div key={p} className="panel p-6"><span className="text-xs font-bold text-sag-gold">PATH {String(i+1).padStart(2,"0")}</span><h3 className="mt-4 text-xl font-semibold">{p}</h3><p className="mt-3 text-sm text-sag-muted">Configured from governed Core and Academy-specific courses according to role, scope and cohort requirements.</p></div>)}</div></div></section>
<section className="section"><div className="shell"><p className="eyebrow">Active course grid</p><h2 className="h2 mt-4">Current registry records for this academy.</h2><div className="mt-8 grid gap-4 lg:grid-cols-2">{active.length?active.map(c=><div key={c.id} className="panel p-5"><div className="flex items-center justify-between"><span className="text-xs font-bold text-sag-gold">{c.id} · v{c.version}</span><span className="text-xs text-sag-muted">{c.status}</span></div><h3 className="mt-3 text-lg font-semibold">{c.title}</h3><p className="mt-2 text-sm leading-6 text-sag-muted">{c.summary}</p></div>):<p className="text-sag-muted">No public course records are released for this academy yet.</p>}</div></div></section>
<section className="section border-y border-slate-800 bg-sag-slate/50"><div className="shell grid gap-6 lg:grid-cols-2"><Info title="Cohort Deployment Options" items={academy.deploymentOptions}/><div className="panel p-7"><p className="eyebrow">The Assurance Difference</p><h2 className="mt-4 text-2xl font-semibold">Learning is governed like an assurance product.</h2><p className="mt-4 text-sag-muted">Source control, exact-version review, human authority, evidence retention, independent verification where required and separated Registrar decisions are built into the lifecycle.</p></div></div></section>
<section className="section"><div className="shell grid gap-6 lg:grid-cols-2"><Info title="Case Scenarios" items={academy.caseScenarios}/><Info title="Faculty Credentials & Practice Areas" items={academy.facultyProfile} note="Faculty assignments are cohort-specific. Published biographies and credentials must be verified before use in a client SOW."/></div></section>
<section id="quote" className="section border-t border-slate-800"><div className="shell max-w-4xl"><p className="eyebrow">Enterprise quote</p><h2 className="h2 mt-4">Configure a {academy.shortName} cohort.</h2><form action="mailto:info@safetyassuranceglobal.com" method="post" encType="text/plain" className="panel mt-8 grid gap-4 p-6 sm:grid-cols-2"><input type="hidden" name="academy" value={academy.name}/><input name="organization" required placeholder="Organization" className="rounded-lg border border-slate-700 bg-slate-950 px-4 py-3"/><input name="email" required type="email" placeholder="Work email" className="rounded-lg border border-slate-700 bg-slate-950 px-4 py-3"/><input name="learners" placeholder="Estimated learner count" className="rounded-lg border border-slate-700 bg-slate-950 px-4 py-3"/><input name="timing" placeholder="Desired delivery window" className="rounded-lg border border-slate-700 bg-slate-950 px-4 py-3"/><textarea name="requirements" required placeholder="Roles, requirements, risks, contract drivers and desired outcomes" className="min-h-36 rounded-lg border border-slate-700 bg-slate-950 px-4 py-3 sm:col-span-2"/><button className="btn-gold sm:col-span-2 sm:justify-self-start">Generate quote request</button></form></div></section>
</>}

function Info({title,items,note}:{title:string;items:string[];note?:string}){return <div className="panel p-7"><h2 className="text-2xl font-semibold">{title}</h2><ul className="mt-5 grid gap-3">{items.map(item=><li key={item} className="flex gap-3 text-sm text-sag-muted"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-sag-gold"/>{item}</li>)}</ul>{note&&<p className="mt-5 border-t border-slate-800 pt-4 text-xs leading-5 text-sag-muted">{note}</p>}</div>}
