import Link from "next/link";
import { ShieldCheck, Fingerprint, Workflow, ArrowRight, Building2, GraduationCap } from "lucide-react";
import AcademyGrid from "@/components/AcademyGrid";
import GovernanceMatrix from "@/components/GovernanceMatrix";
import ValueChainDiagram from "@/components/ValueChainDiagram";
import PipelineDiagram from "@/components/PipelineDiagram";

export default function Home(){return <>
<section className="relative overflow-hidden border-b border-slate-800 bg-grid-dark bg-[size:36px_36px]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,rgba(37,99,235,.2),transparent_34%),radial-gradient(circle_at_18%_70%,rgba(245,158,11,.09),transparent_25%)]"/><div className="shell relative grid min-h-[720px] items-center gap-12 py-20 lg:grid-cols-[1.15fr_.85fr]"><div><p className="eyebrow">Safety Assurance Global · Institute of Assurance</p><h1 className="h1 mt-5 max-w-5xl">Evidence-backed learning for organizations where safety, quality, resilience, and leadership matter.</h1><p className="copy mt-7 max-w-3xl">A governed workforce education system connecting field assurance, controlled course production, human review, runtime evidence, Registrar authority and continuous improvement.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/enterprise#request" className="btn-gold">Request Enterprise Cohort <ArrowRight className="ml-2" size={17}/></Link><Link href="/courses" className="btn-outline">Explore Course Registry</Link></div><p className="mt-5 text-xs uppercase tracking-[.18em] text-sag-muted">Powered by Mandavere · Edge-delivered enterprise experience</p></div><div className="panel p-7 shadow-gold"><div className="flex items-center gap-3"><ShieldCheck className="text-sag-gold"/><p className="font-semibold">Assurance architecture</p></div><div className="mt-6 grid gap-3">{[["Governed sources","Exact-version traceability"],["Human authority","Mandatory review at release-critical gates"],["Evidence engine","Completion, scoring and audit-chain records"],["Credential separation","Registrar-controlled issuance decision"]].map(([a,b])=><div key={a} className="rounded-xl border border-slate-800 bg-slate-950/70 p-4"><p className="text-sm font-semibold">{a}</p><p className="mt-1 text-sm text-sag-muted">{b}</p></div>)}</div></div></div></section>
<section className="section"><div className="shell"><p className="eyebrow">Eleven specialized academies</p><h2 className="h2 mt-4 max-w-3xl">One Institute architecture. Multiple operational domains.</h2><p className="copy mt-5 max-w-3xl">Shared core, governed reuse, sector depth and consistent evidence controls across the complete learning system.</p><div className="mt-10"><AcademyGrid/></div></div></section>
<section className="section border-y border-slate-800 bg-sag-slate/50"><div className="shell"><p className="eyebrow">Course Factory</p><h2 className="h2 mt-4">G0–G11 production gates</h2><p className="copy mt-5 max-w-3xl">AI can accelerate structured drafting and analysis. It does not replace mandatory human review, independent verification, Registrar authority or executive release decisions.</p><div className="mt-10"><GovernanceMatrix/></div></div></section>
<section className="section"><div className="shell space-y-10"><div><p className="eyebrow">Governed value chain</p><h2 className="h2 mt-4">From market need to controlled improvement.</h2></div><ValueChainDiagram/><div className="pt-6"><p className="eyebrow">Non-duplication architecture</p><h2 className="h2 mt-4">Reuse the governed source before creating another object.</h2></div><PipelineDiagram/></div></section>
<section className="section border-y border-slate-800 bg-sag-slate/50"><div className="shell grid gap-6 lg:grid-cols-3"><div className="panel p-7"><Fingerprint className="text-sag-glow"/><h3 className="mt-5 text-xl font-semibold">Defensible Evidence Engine</h3><p className="mt-3 text-sm leading-6 text-sag-muted">Version-pinning, completion timestamps, threshold evidence, cryptographic hashing and audit-log design support exact-version traceability.</p></div><div className="panel p-7"><Workflow className="text-sag-glow"/><h3 className="mt-5 text-xl font-semibold">Consulting ↔ Learning Flywheel</h3><p className="mt-3 text-sm leading-6 text-sag-muted">Field assurance and owner-representative work identify real operational needs; governed learning converts recurring lessons into controlled workforce capability.</p></div><div className="panel p-7"><Building2 className="text-sag-glow"/><h3 className="mt-5 text-xl font-semibold">Enterprise Deployment</h3><p className="mt-3 text-sm leading-6 text-sag-muted">Private cohorts, tenant-isolated overlays, evidence reporting and role-based pathways designed for complex organizations and public-sector programs.</p></div></div></section>
<section className="section"><div className="shell panel grid gap-8 p-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="eyebrow">Enterprise cohorts</p><h2 className="mt-3 text-3xl font-semibold">Build the learning system around your operational risk.</h2><p className="mt-4 max-w-3xl text-sag-muted">Define roles, controlled pathways, evidence requirements, delivery model and reporting cadence with SAG.</p></div><Link href="/enterprise#request" className="btn-gold"><GraduationCap className="mr-2" size={18}/>Request Cohort</Link></div></section>
</>}
